[workspace]
resolver = "3"
members = ["main","wimpy"]

[workspace.dependencies]
winit = "0.30.12"
anyhow = "1.0.100"
image = "0.25.9"
rand = "0.9.2"
wgpu = "27.0.1"
log = "0.4.28"
bytemuck = {version = "1.24.0",features = ["derive"]}
cgmath = "0.18.0"
