[workspace]
resolver = "3"
members = ["wimpy-engine","wimpy-native","wimpy-web"]

[workspace.dependencies]
anyhow = "1.0.100"
wgpu = "27.0.1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
