[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
wimpy = { path = "../wimpy" }
log = { workspace = true }
env_logger = "0.11.8"
winit = { workspace = true }
anyhow = { workspace = true }
