[package]
name = "wimpy"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
collections = { path = "../collections" }
generational-arena = "0.2"
wgpu = { workspace = true }
log = { workspace = true }
